### ISSUE TITLE
Write tests for different versions of Popularity-based algorithms

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [FilWisher/distributed-project#30]

**Comment by Hugh-OBrien** [comment]
Tests needed for:
-  'Pop_neighbour_stat',
-  'Pop_self_stat',
-  'Pop_neighbour_t_stat',
-  'Pop_neighbour_dyn',
-  'Pop_self_dyn',
-  'Pop_neighbour_t_dyn'

**Comment by Hugh-OBrien** [comment]
This is done!
